"""Declarative base and the column conventions shared by every table.

Mixins here define the two properties every row in this system has: a surrogate UUID key that is
safe to expose in URLs, and creation/modification timestamps used for auditing and sorting.

声明式基类与全表通用的列约定。此处的 Mixin 定义了系统中每行数据共有的两项属性：
可安全暴露于 URL 的 UUID 代理主键，以及用于审计与排序的创建/修改时间戳。
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, Uuid, func
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON

# Explicit constraint naming lets Alembic autogenerate stable names instead of database defaults,
# which keeps migrations reversible across environments.
# 显式约束命名使 Alembic 生成稳定名称而非数据库默认名，保证迁移在各环境间可逆。
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# JSONB on PostgreSQL, plain JSON elsewhere so the test suite can run on SQLite.
# PostgreSQL 上使用 JSONB，其他方言退回普通 JSON，以便测试套件在 SQLite 上运行。
JsonColumn = JSON().with_variant(postgresql.JSONB(), "postgresql")


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UuidPrimaryKeyMixin:
    """Surrogate primary key generated by the application rather than the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampMixin:
    """Server-maintained creation and modification instants."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
