"""Baseline schema: identity, organization, documents, activities, and notifications.

Revision ID: 949a703fb8f4
Revises:
Create Date: 2026-09-21

JSON columns are declared with a JSONB variant so PostgreSQL gets indexable binary JSON while the
test suite can still run the same metadata on SQLite.

JSON 列声明为 JSONB 变体：PostgreSQL 使用可索引的二进制 JSON，
同一套元数据仍可在 SQLite 上供测试套件运行。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '949a703fb8f4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_zh', sa.String(length=120), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('summary_zh', sa.Text(), nullable=True),
    sa.Column('accent_color', sa.String(length=9), nullable=False),
    sa.Column('portal_modules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('has_organization_oversight', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], name=op.f('fk_department_parent_id_department'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('slug', name=op.f('uq_department_slug'))
    )
    op.create_table('user_account',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=120), nullable=False),
    sa.Column('chinese_name', sa.String(length=60), nullable=True),
    sa.Column('preferred_name', sa.String(length=60), nullable=True),
    sa.Column('pronouns', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'REJECTED', name='account_status', native_enum=False, length=32), nullable=False),
    sa.Column('affiliation', sa.Enum('STUDENT', 'ALUMNUS', name='affiliation_type', native_enum=False, length=16), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('enrolment_year', sa.Integer(), nullable=True),
    sa.Column('program_of_study', sa.String(length=160), nullable=True),
    sa.Column('campus', sa.String(length=60), nullable=True),
    sa.Column('requested_department_slug', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('wechat_id', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receives_daily_digest', sa.Boolean(), nullable=False),
    sa.Column('receives_activity_notices', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email'))
    )
    op.create_index('ix_user_account_status_graduation', 'user_account', ['status', 'graduation_year'], unique=False)
    op.create_table('activity',
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='activity_status', native_enum=False, length=16), nullable=False),
    sa.Column('audience', sa.Enum('DEPARTMENT', 'ALL_MEMBERS', 'ALUMNI', 'PUBLIC', name='activity_audience', native_enum=False, length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_activity_created_by_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_activity_department_id_department'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_index('ix_activity_schedule', 'activity', ['status', 'starts_at'], unique=False)
    op.create_table('alumni_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('degree', sa.String(length=160), nullable=True),
    sa.Column('current_employer', sa.String(length=160), nullable=True),
    sa.Column('current_role', sa.String(length=160), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('personal_site_url', sa.String(length=300), nullable=True),
    sa.Column('expertise_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('open_to_mentorship', sa.Boolean(), nullable=False),
    sa.Column('open_to_referrals', sa.Boolean(), nullable=False),
    sa.Column('is_discoverable', sa.Boolean(), nullable=False),
    sa.Column('message_to_students', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_alumni_profile_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alumni_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_alumni_profile_user_id'))
    )
    op.create_table('announcement',
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('audience', sa.Enum('DEPARTMENT', 'ALL_MEMBERS', 'ALUMNI', 'PUBLIC', name='activity_audience', native_enum=False, length=16), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_account.id'], name=op.f('fk_announcement_author_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_announcement_department_id_department'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement'))
    )
    op.create_index('ix_announcement_department_published', 'announcement', ['department_id', 'published_at'], unique=False)
    op.create_table('audit_log_entry',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('REGISTRATION_APPROVED', 'REGISTRATION_REJECTED', 'ACCOUNT_SUSPENDED', 'ACCOUNT_REACTIVATED', 'MEMBERSHIP_GRANTED', 'MEMBERSHIP_REVOKED', 'MEMBERSHIP_ROLE_CHANGED', 'PRIMARY_DEPARTMENT_CHANGED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'DOCUMENT_DELETED', 'BROADCAST_SENT', name='audit_action', native_enum=False, length=40), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], name=op.f('fk_audit_log_entry_actor_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_audit_log_entry_department_id_department'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entry'))
    )
    op.create_index('ix_audit_log_entry_target', 'audit_log_entry', ['target_type', 'target_id'], unique=False)
    op.create_table('course_enrolment',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_code', sa.String(length=24), nullable=False),
    sa.Column('course_title', sa.String(length=200), nullable=True),
    sa.Column('section_code', sa.String(length=24), nullable=True),
    sa.Column('term_code', sa.String(length=12), nullable=False),
    sa.Column('meeting_weekdays', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('instructor', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_course_enrolment_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_enrolment'))
    )
    op.create_index('ix_course_enrolment_user_term', 'course_enrolment', ['user_id', 'term_code', 'is_active'], unique=False)
    op.create_table('document_category',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_zh', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('GOVERNANCE', 'PLANNING', 'FINANCE', 'SPONSORSHIP', 'PUBLICITY', 'ACADEMIC', 'ARCHIVE', name='document_kind', native_enum=False, length=24), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_system_managed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_document_category_department_id_department'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_category.id'], name=op.f('fk_document_category_parent_id_document_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_category')),
    sa.UniqueConstraint('department_id', 'parent_id', 'slug', name='uq_document_category_slug_in_parent')
    )
    op.create_table('email_delivery_log',
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('template_key', sa.Enum('VERIFICATION_CODE', 'PASSWORD_RESET_CODE', 'REGISTRATION_APPROVED', 'REGISTRATION_REJECTED', 'ACTIVITY_ANNOUNCEMENT', 'DEPARTMENT_BROADCAST', 'DAILY_DIGEST', name='email_template_key', native_enum=False, length=32), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'SKIPPED', name='email_delivery_status', native_enum=False, length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('digest_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user_account.id'], name=op.f('fk_email_delivery_log_recipient_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_delivery_log'))
    )
    op.create_index('ix_email_delivery_log_digest_run', 'email_delivery_log', ['template_key', 'digest_date', 'recipient_email'], unique=False)
    op.create_table('email_verification_code',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTRATION', 'PASSWORD_RESET', 'EMAIL_CHANGE', name='verification_purpose', native_enum=False, length=24), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_email_verification_code_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_code'))
    )
    op.create_index('ix_email_verification_code_lookup', 'email_verification_code', ['email', 'purpose', 'consumed_at'], unique=False)
    op.create_table('refresh_session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_to_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_refresh_session_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_session')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_refresh_session_token_digest'))
    )
    op.create_index('ix_refresh_session_user_active', 'refresh_session', ['user_id', 'revoked_at'], unique=False)
    op.create_table('role',
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_zh', sa.String(length=120), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('DEPARTMENT', 'ORGANIZATION', name='grant_scope', native_enum=False, length=16), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_system_managed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_role_department_id_department'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('key', name=op.f('uq_role_key'))
    )
    op.create_table('department_membership',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('title_en', sa.String(length=120), nullable=True),
    sa.Column('title_zh', sa.String(length=120), nullable=True),
    sa.Column('term_label', sa.String(length=32), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_department_membership_department_id_department'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_department_membership_role_id_role'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_department_membership_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_membership')),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_department_membership_user_dept')
    )
    op.create_table('document',
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.Enum('DEPARTMENT', 'ORGANIZATION', 'PRESIDIUM_ONLY', name='document_visibility', native_enum=False, length=24), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['document_category.id'], name=op.f('fk_document_category_id_document_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_document_department_id_department'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user_account.id'], name=op.f('fk_document_uploaded_by_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index('ix_document_department_category', 'document', ['department_id', 'category_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission', name=op.f('pk_role_permission')),
    sa.UniqueConstraint('role_id', 'permission', name='uq_role_permission_pair')
    )
    op.create_table('document_version',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_version_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user_account.id'], name=op.f('fk_document_version_uploaded_by_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version'))
    )
    op.create_index('ix_document_version_document_number', 'document_version', ['document_id', 'version_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_version_document_number', table_name='document_version')
    op.drop_table('document_version')
    op.drop_table('role_permission')
    op.drop_index('ix_document_department_category', table_name='document')
    op.drop_table('document')
    op.drop_table('department_membership')
    op.drop_table('role')
    op.drop_index('ix_refresh_session_user_active', table_name='refresh_session')
    op.drop_table('refresh_session')
    op.drop_index('ix_email_verification_code_lookup', table_name='email_verification_code')
    op.drop_table('email_verification_code')
    op.drop_index('ix_email_delivery_log_digest_run', table_name='email_delivery_log')
    op.drop_table('email_delivery_log')
    op.drop_table('document_category')
    op.drop_index('ix_course_enrolment_user_term', table_name='course_enrolment')
    op.drop_table('course_enrolment')
    op.drop_index('ix_audit_log_entry_target', table_name='audit_log_entry')
    op.drop_table('audit_log_entry')
    op.drop_index('ix_announcement_department_published', table_name='announcement')
    op.drop_table('announcement')
    op.drop_table('alumni_profile')
    op.drop_index('ix_activity_schedule', table_name='activity')
    op.drop_table('activity')
    op.drop_index('ix_user_account_status_graduation', table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('department')
    # ### end Alembic commands ###
